import { api } from './AxiosService.js'

/**
 * Service for uploading files to Azure Blob Storage
 * Uses SAS tokens generated by the backend
 */
export class AzureBlobClient {
  /**
   * Get a SAS token from the backend for uploading
   * @param {string} containerName - Name of blob container (default: 'uploads')
   * @param {number} expiryMinutes - Token expiry time in minutes (default: 30)
   * @returns {Promise<string>} SAS URL with token
   */
  static async getSasToken(containerName = 'uploads', expiryMinutes = 30) {
    try {
      const response = await api.get('/auth/blob-sas-token', {
        params: {
          containerName,
          expiryMinutes
        }
      })
      return response.data.sasUrl
    } catch (error) {
      console.error('Error getting SAS token:', error)
      throw error
    }
  }

  /**
   * Upload a file to Azure Blob Storage
   * @param {File} file - File to upload
   * @param {string} containerName - Name of blob container
   * @param {string} blobName - Name for blob in storage (optional, defaults to filename)
   * @returns {Promise<string>} URL of uploaded blob
   */
  static async uploadFile(file, containerName = 'uploads', blobName = null) {
    try {
      // Get SAS token
      const sasToken = await this.getSasToken(containerName)

      // Get base URL from SAS token
      const baseUrl = sasToken.split('?')[0]
      const fileName = blobName || file.name

      // Construct full blob URL
      const blobUrl = `${baseUrl}/${fileName}`

      // Upload file using put request to blob URL with SAS token
      const response = await fetch(blobUrl, {
        method: 'PUT',
        headers: {
          'x-ms-blob-type': 'BlockBlob',
          'Content-Type': file.type || 'application/octet-stream'
        },
        body: file
      })

      if (!response.ok) {
        throw new Error(`Upload failed with status ${response.status}`)
      }

      // Return blob URL without SAS token (can be stored in DB and accessed later)
      return `${baseUrl}/${fileName}`
    } catch (error) {
      console.error('Error uploading file to Azure:', error)
      throw error
    }
  }

  /**
   * Upload blob (e.g., canvas screenshot) to Azure Blob Storage
   * @param {Blob} blob - Blob to upload
   * @param {string} containerName - Name of blob container
   * @param {string} blobName - Name for blob in storage
   * @returns {Promise<string>} URL of uploaded blob
   */
  static async uploadBlob(blob, containerName = 'uploads', blobName) {
    if (!blobName) {
      throw new Error('Blob name is required')
    }

    const file = new File([blob], blobName, { type: blob.type })
    return this.uploadFile(file, containerName, blobName)
  }

  /**
   * Generate a unique filename based on timestamp
   * @param {string} prefix - Optional prefix for filename
   * @param {string} extension - File extension (default: 'stl')
   * @returns {string} Generated filename
   */
  static generateFileName(prefix = 'file', extension = 'stl') {
    const timestamp = Date.now()
    const random = Math.random().toString(36).substring(2, 8)
    return `${prefix}-${timestamp}-${random}.${extension}`
  }
}
